version: '3.7'

services:
  # MongoDB
  cadmus-tgr-mongo:
    image: mongo
    container_name: cadmus-tgr-mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    command: mongod --logpath=/dev/null # --quiet
    ports:
      - 27017:27017
    networks:
      - cadmus-tgr-network

 # PostgreSQL
  cadmus-tgr-pgsql:
    image: postgres
    container_name: cadmus-tgr-pgsql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    networks:
      - cadmus-tgr-network
    # volumes:
      # ensure you have created the var/db/pgsql folder in the host
      # https://hub.docker.com/r/postgis/postgis
      # - /var/db/pgsql:/var/lib/postgresql/data

  # Cadmus TGR API
  cadmus-tgr-api:
    image: vedph2020/cadmus-tgr-api:5.0.1
    container_name: cadmus-tgr-api
    ports:
      # https://stackoverflow.com/questions/48669548/why-does-aspnet-core-start-on-port-80-from-within-docker
      - 59590:80
    depends_on:
      - cadmus-tgr-mongo
      - cadmus-tgr-pgsql
    environment:
      # for Windows use : as separator, for non Windows use __
      # (see https://github.com/aspnet/Configuration/issues/469)
      - CONNECTIONSTRINGS__DEFAULT=mongodb://cadmus-tgr-mongo:27017/{0}
      - CONNECTIONSTRINGS__INDEX=Server=cadmus-tgr-pgsql;port=5432;Database={0};User Id=postgres;Password=postgres;Include Error Detail=True
      - SEED__INDEXDELAY=25
      - MESSAGING__APIROOTURL=http://cadmusapi.azurewebsites.net
      - MESSAGING__APPROOTURL=http://cadmusapi.com/
      - MESSAGING__SUPPORTEMAIL=support@cadmus.com
      - SERILOG__CONNECTIONSTRING=mongodb://cadmus-tgr-mongo:27017/{0}-log
      - STOCKUSERS__0__PASSWORD=P4ss-W0rd!
    networks:
      - cadmus-tgr-network

  # Cadmus app
  cadmus-tgr-app:
    image: vedph2020/cadmus-tgr-app:3.0.1
    container_name: cadmus-tgr-app
    ports:
      - 4200:80
    depends_on:
      - cadmus-tgr-api
    networks:
      - cadmus-tgr-network

networks:
  cadmus-tgr-network:
    driver: bridge
